#! /usr/bin/perl
# -*- coding: utf-8 -*-
# Time-stamp: "2021-02-11 17:23:30 queinnec"

use strict;
use utf8;

print "// Automatically generated by hack-sax.pl
export const sax = {};\n\n";

while ( <> ) {
    next if ( /^;\(function \(sax/ );
    if ( /^\}\).*typeof exports/ ) {
        print "\n// end of sax.mjs\n";
        last;
    }
    print;
}

# end of hack-sax.pl
