#! /usr/bin/perl
# -*- coding: utf-8 -*-
# Time-stamp: "2021-02-11 18:32:37 queinnec"

use strict;
use utf8;

print "// Automatically generated by hack-sax.pl
export const sax = {};\n\n";

while ( <> ) {
    # 1st line
    next if ( /^;\(function \(sax/ );

    if ( /require.*array-helper.*[.]isArray/ ) {
        s@require\('./array-helper'\).isArray@Array.isArray@g;
    }

    if ( /^\}\).*typeof exports/ ) {
        print "\n// end of sax.mjs\n";
        last;
    }
    print;
}

# end of hack-sax.pl
