#! /usr/bin/perl
# -*- coding: utf-8 -*-
# Time-stamp: "2021-02-11 17:57:47 queinnec"

use strict;
use utf8;

print "// Automatically generated by hack-xml2js.pl
export let convert = undefined;\n\n";

while ( <> ) {
    if ( /require\('sax'\)/ ) {
        $_ = "import { sax } from 'codegradx/src/sax';\n";
    }
    if ( /module.exports =/ ) {
        s@module.exports@convert@;
    }
    print;
}

# end of hack-xml2js.pl
