#! /usr/bin/perl
# -*- coding: utf-8 -*-
# Time-stamp: "2021-02-12 09:22:38 queinnec"

use strict;
use utf8;

print "// Automatically generated by hack-xml2js.pl
export let convert = {};\n\n";

while ( <> ) {
    chomp;
    if ( /require\('sax'\)/ ) {
        $_ = "import { sax } from 'codegradx/src/sax';";
    }
    if ( /require.*options-helper/ ) {
        $_ = "import * as helper from 'codegradx/src/options-helper';";
    }
    if ( /require.*array-helper.*[.]isArray/ ) {
        s@require\('./array-helper'\).isArray@Array.isArray@g;
    }
    if ( /module.exports =/ ) {
        s@module.exports@convert.xml2js@;
    }
    print "$_\n";
}

# end of hack-xml2js.pl
