#! /usr/bin/perl
# -*- coding: utf-8 -*-
# Time-stamp: "2021-09-15 18:17:27 queinnec"

use strict;
use utf8;

print "// Automatically generated by hack-xml2js.pl
/*eslint no-prototype-builtins: off*/
";

while ( <> ) {
    chomp;
    s@@@g;
    if ( /require\('sax'\)/ ) {
        $_ = "import { sax } from './sax.mjs';";
    }
    if ( /require.*options-helper/ ) {
        $_ = "import { helper } from './options-helper.mjs';";
    }
    if ( /require.*array-helper.*[.]isArray/ ) {
        s@require\('./array-helper'\).isArray@Array.isArray@g;
    }
    if ( /module.exports =/ ) {
        s@module.exports@export const xml2js@;
    }
    print "$_\n";
}

# end of hack-xml2js.pl
